### PR TITLE
add plate tectonic stats + more documentation

### PR DESCRIPTION
**Pull request by laurilano**
Documented `reconstruct_to_birth_age`.

Added the `test_plate_tectonic_stats` function to `reconstruction.py`, using the object rotation model and topology feature collection. So far it returns an array with each row corresponding to stats for each reconstruction time, and columns corresponding to:
1. Reconstruction time (Ma)
2. Total length of all mid-ocean ridges (km)
3. Ridge mean spreading velocity (spreading rate) (cm/yr)
4. Ridge mean spreading velocity standard deviation (cm/yr)
5. Crustal surface area produced over 1 yr at ridges (km^2/yr)
6. Total length of all subduction zones (km)
7. Subduction mean velocity (convergence rate) (cm/yr)
8. Subduction mean velocity standard deviation (cm/yr) 
9. Crustal surface area subducted by trenches over 1 yr (km^2/yr)
10. Length of all transform boundaries (km)

However, I have not yet implemented value bounds or a pass/fail scheme. How should this look like?

### CODE REVIEW

**Comment by laurilano** [comment]
Added `get_plate_tectonic_stats` and 'plot_plate_tectonic_stats_differences` to the PlateReconstruction object in `reconstruction.py`. 

Features of `get_plate_tectonic_stats`:
- Obtains plate tectonic stats of the plate model ascribed to `PlateReconstruction`
- Returns an array of stats by default, but now offers a CSV output by setting `return_csv = True`. 

Features of 'plot_plate_tectonic_stats_differences`:
- Plots comparisons of plate tectonic stats between 2 models for a given set of geological min times, max times and delta times. The user can choose which stats to compare using a data indices array: i.e. if given [1,5], the function plots 1 - Total length of all mid-ocean ridges (km), 5 - Total length of all subduction zones (km). 
- Accepts 1 or 2 full paths to a CSV file of plate tectonic stats (optimally, the output of `get_plate_tectonic_stats` above).
- If 1 CSV file is given, the function assumes the user wants to compare against the Muller2019 plate tectonic stats.
- If 2 CSV files are given, the function compares both.
- Plots two images by default: 1) Plate tectonic stats of both models vs time (One plot), 2) differences in plate tectonic stats for both models vs time (a subplot beneath plot 1)). 
- Should a user want to save the plots locally, the function accepts a **save location** for the plots. If a filename is provided, the function overwrites it with a default name.

**Comment by brmather** [comment]
@lauren-ilano or @laurilano can you comment on these issues I have highlighted? Cheers!

**Comment by laurilano** [comment]
> @lauren-ilano or @laurilano can you comment on these issues I have highlighted? Cheers!

Hi Ben, yep I'm on it! Currently figuring out the most efficient way to present the code :)

**Comment by brmather** [comment]
@laurilano - should this PR still be active or have you implemented this code somewhere else?

**Comment by laurilano** [comment]
> @laurilano - should this PR still be active or have you implemented this code somewhere else?

The updates for this PR are in the other PR for the `plate-tectonic-stats-new` branch (#16). This PR can be discarded.

**Pull request closed without merging**
