### PR TITLE
Raster reconstruction changes

### PR DESCRIPTION
**Pull request by cpalfonso**
`gplately.grids.reconstruct_grid` now uses `scipy.spatial.transform.Rotation` to perform rotations and `scipy.spatial.cKDTree` for nearest-neighbour interpolation after rotation.

### CODE REVIEW

**Comment by cpalfonso** [comment]
To do:
- [ ] Update documentation?
- [ ] Re-run (and possibly modify) `Notebooks/06-Rasters.ipynb`

**Comment by cpalfonso** [comment]
N.B. Now that raster reconstruction is implemented using `scipy.spatial.transform.Rotation`, it will probably be slower for anyone using a version of SciPy prior to 1.6.0 (released on 1st January 2021) due to [changes to the rotation implementation](https://docs.scipy.org/doc/scipy/release.1.6.0.html#scipy-spatial-improvements). It might be worth bumping our SciPy requirement up to this version; the downside would be that we could no longer support Python versions <3.7.
Incidentally, this would also mean that we could start adding type hints to the code, since they were introduced back in 2015 with [Python 3.5](https://docs.python.org/3/library/typing.html).

@brmather what do you think?

**Comment by brmather** [comment]
This all looks good, @cpalfonso. Can you confirm if the rasters are being reconstructed correctly with plate models other than Muller et al 2019?

 I don't think we should enforce people to use scipy >= 1.6 since `scipy.spatial.transform.Rotation` will run for older versions (albeit with a performance penalty). I'm also not convinced on the utility of type hints. Python was designed to allow users to code fast and loose with types, avoiding the strictness of compiled languages like C. That being said, if you can point to some code which would benefit from having type hints then I'm open to it. Enforcing python 3.5+ would be fine since it's been around for so long.

**Comment by brmather** [comment]
@cpalfonso all good to merge?

**Comment by cpalfonso** [comment]
@brmather just re-running a couple of notebooks now; it should be ready to go soon.

**Pull request merged**
