### PR TITLE
motion paths and flowlines

### PR DESCRIPTION
**Pull request by laurilano**
Added two new functions to `PlateReconstruction`:
1) `create_motion_path`: outputs lats, lons (ndarrays of lats and lons for n seed point motion paths) and rate_of_motion (an array of plate speeds adapted from pygplates sample noteooks);
2) `create_flowline`: outputs left and right lats and lons (4 ndarrays)
Both accept an array of latitudes and longitudes, an array of reconstruction times, and necessary plate IDs.

Added notebook 09 to demonstrate these functionalities.

### CODE REVIEW

**Comment by brmather** [comment]
Hi @lauren-ilano @laurilano 

I have made some minor edits to `reconstruction.py` and the notebook, mainly to bring the motion path functionality across to `gplately.Points` object. Some things to be aware of that I have addressed:

1. when calculating velocity, the spacing between time points may not be linear - fixed with `np.diff`.
2. you should not routinely add on 360 degrees to all Lons < 0. This is only necessary for plotting across the 180 meridian.
3. these routines should be able to run for single points / times.
4. we should use `anchor_plate_id` consistently to avoid confusion.

I have simplified a lot of the plotting in the first notebook. Can you update the other plots? Also flow lines haven't been updated to address (3). Maybe you can also tackle that.

**Comment by laurilano** [comment]
Hi @brmather ,

I have updated `Points` to include a `flow_line()` function (addressing 3). This is demonstrated in the now-updated Notebook 09. The plot outputs are identical for `PlateReconstruction` and `Points`, but the ones shown are from`Points`. 
Since the European Craton motion paths example involves 3 points, I have left the `for` loop in its plotting routine so that each column in the lat and lon ndarray is plotted individually with the `time_array` colormap. 

In `pygplates.Feature.create_motion_path()` I made the time array `[float(t) for t in time_array]` to ensure that the times are floats to match pygplates' C++ signature. I also enforced `int()` for the plate IDs, and `float()` for the valid time tuple.

**Comment by laurilano** [comment]
Added new functions to `PlotTopologies` for plotting shapely lines with the following miscellaneous feature types:

- gpml:ContinentalCrust
- gpml:ContinentalRift
- gpml:ExtendedContinentalCrust
- gpml:Fault
- gpml:FractureZone
- gpml:InferredPaleoBoundary
- gpml:OrogenicBelt
- gpml:PassiveContinentalBoundary
- gpml:SlabEdge
- gpml:Suture
- gpml:TerraneBoundary
- gpml:Transform
- gpml:TransitionalCrust
- gpml:UnclassifiedFeature

These have already been resolved when initialising `PlotTopologies`.

**Comment by brmather** [comment]
I've made some efficiency improvements for the flow lines calculation.

**Pull request merged**
