### PR TITLE
Expansions

### PR DESCRIPTION
**Pull request by laurilano**
Added a sample "Data" folder for all required files as well as 3 sample Jupyter notebooks:
- 02-PlateReconstructions
- 03-WorkingWithPoints
- 04-VelocityBasics

Added documentation to the following modules:

- reconstruction (incl. PlateReconstruction, Points objects)
- plot (incl. PlotTopologies object)
- grids (incl. RegularGridInterpolator, Raster objects)
- tools

### CODE REVIEW

**Comment by brmather** [comment]
Excellent documentation and example notebooks! This is good stuff! Just a few minor comments:

- In notebook 4 under scatter plot, you should not need to compute the velocities using PTT. I think you should just be able to define points on a grid then use `model.get_plate_velocities()` to get velocities. Alternatively set up a `Point` object using the grid of points on the sphere and use the `plate_velocity()` method.
- There appears to be some duplication in the data folder e.g. the workshop directory. For now we only want files compatible with _Muller et al._ 2019. In the future I would like to implement a downloader that grabs the reconstruction files you request on-the-fly a-la Cartopy's [feature download](https://github.com/SciTools/cartopy/blob/master/tools/cartopy_feature_download.py).

Once these are addressed I'll merge your PR into the master branch.

**Comment by jcannon-gplates** [comment]
Just saw the comment about _feature download_. Simon Williams uses a library called pooch which downloads and caches - you can see how he loads _Muller et al. 2019_ [here](https://github.com/siwill22/GPlatesReconstructionModel/blob/dc29746d073050987fc91258b7786f1074df8efa/gprm/datasets/Reconstructions.py#L174) in case it's of use in the future (I've not used it yet).

**Comment by brmather** [comment]
Thanks @jcannon-gplates! I was not aware of Pooch or Simon's python library. Agreed, Pooch is exactly what we need. I like that it stores files in `os_cache`, so you need only to download the reconstruction files, coastlines, etc once. @lauren-ilano - can you give pooch a test drive to see if it works effectively?

By the way John, feel free to contribute to this repo - your ideas are valued and appreciated! I'm hoping gplately will be a team effort! :handshake:

**Comment by laurilano** [comment]
Added another tutorial Notebook:

- 05-WorkingWithFeatureGeometries

Cleaned sample "Data" folder - now only includes files used in the Notebooks such as:

- The "Muller_etal_2019_PlateMotionModel_v2.0_Tectonics" directory for all notebooks so far;

...and the following GPML features used in the new Notebook: 

- The "SeafloorFabric" directory;
- The "Hotspots_Compilation_Whittaker_etal.gpmlz" GPML feature;
- The "Johansson_etal_2018_VolcanicProvinces_v2.gpmlz" GPML feature; and
- The "Whittaker_etal_2015_LIPs.gpmlz" GPML feature

**Comment by brmather** [comment]
I have removed the sample data folder because:

1. It blows out the size of the repository considerably
2. I am convinced pooch is the best way of retrieving data files

I have cherry picked all the changes minus the data file commits into #5

**Pull request closed without merging**
